Repository isfit/App-isfit-25, pull requests merged in 2024-10, with the labels that each got.

#30 fix: updated from 2023 to 2025 (#8)
  src/screens/FAQScreen.js
  src/screens/data/faqData.js
Labels: update

#22 feat: add update package documentation (#21)
  README.md
Labels: documentation

#23 feat: add new launsch screens randomly (#6)
  App.js
  src/assets/LaunchScreens/cloudblue_black.png
  src/assets/LaunchScreens/cloudblue_white.png
  src/assets/LaunchScreens/lightblue_blue.png
  src/assets/LaunchScreens/pink_white.png
  src/assets/LaunchScreens/red_black.png
  src/assets/LaunchScreens/red_white.png
  src/assets/LaunchScreens/white_black.png
  src/assets/LaunchScreens/white_blue.png
Labels: enhancement, update

#31 fix: change back button theme page (#19)
  package-lock.json
  package.json
  src/components/Header.js
Labels: bug, enhancement

#44 fix: programatically change launch screen using custom font (#24)
  App.js
  app.json
  package-lock.json
  package.json
  src/assets/LaunchScreens/cloudblue_black.png
  src/assets/LaunchScreens/cloudblue_white.png
  src/assets/LaunchScreens/lightblue_blue.png
  src/assets/LaunchScreens/pink_white.png
  src/assets/LaunchScreens/red_black.png
  src/assets/LaunchScreens/red_white.png
  src/assets/LaunchScreens/white_black.png
  src/assets/LaunchScreens/white_blue.png
  src/assets/fonts/HVD_Rowdy.otf
Labels: fix, update, maintenance

#46 fix: enabled map on Android (#15)
  App.js
Labels: fix
