Repository isfit/App-isfit-25, pull requests merged in 2024-11, with the labels that each got.

#57 fix:added border to map marker(#56)
  src/assets/ExploreTrondheim/map-marker.png
Labels: fix

#71 add default header to MarkerInfoScreen and InformationScreen
  App.js
  app.json
  package-lock.json
  package.json
  src/assets/ExploreTrondheim/listicon.png
  src/assets/ExploreTrondheim/mapicon.png
  src/components/AttractionMarkerBox.js
  src/components/Header.js
  src/components/MarkerInfo.js
  src/screens/AttractionBoxInfoScreen.js
  src/screens/AttractionBoxScreen.js
  src/screens/InformationScreen.js
  src/screens/MapScreen.js
  src/screens/MarkerInfoScreen.js
  src/screens/listicon.png
  yarn.lock
Labels: enhancement

#79 add animated user location icon
  package-lock.json
  package.json
  src/components/MapWithMarkers.js
  yarn.lock
Labels: enhancement

#81 add more places
  src/assets/ExploreTrondheim/Eat/robata.png
  src/assets/ExploreTrondheim/Shopping/trondheimTorgCenter.png
  src/assets/ExploreTrondheim/Trondheim101/lerkendal.png
  src/assets/ExploreTrondheim/map-marker.png
  src/assets/attractionMarkers.js
Labels: enhancement

#83 fix: location distance bug
  src/components/MapWithMarkers.js
Labels: bug

#85 84 add location button
  src/components/MapWithMarkers.js
  yarn.lock
Labels: enhancement

#89 fix image path
  src/assets/attractionMarkers.js
Labels: bug

#92 moved duplicate code to utils
  src/components/MapWithMarkers.js
  src/screens/AttractionBoxScreen.js
  src/screens/MapScreen.js
  src/utils/ExploreUtils.js
Labels: enhancement

#95 feat: filter state context (#90)
  App.js
  src/components/MarkerInfo.js
  src/context/FilterContext.js
  src/screens/AttractionBoxScreen.js
  src/screens/MapScreen.js
  src/utils/ExploreUtils.js
Labels: enhancement
